from app import db

## All the models for the app
# like User , Books , etc

## LIBRARIAN 
# ID PRIMARY KEY , UNIQUE, AUTOINCREMENT, NOT NULL
# NAME VARCHAR(100) NOT NULL
# USERNAME/EMAIL VARCHAR(100) NOT NULL
# PASSWORD VARCHAR(100) NOT NULL
# * Sections RELATIONSHIP to SECTION
# * Books RELATIONSHIP to BOOK

## USER
# ID PRIMARY KEY , UNIQUE, AUTOINCREMENT, NOT NULL
# NAME VARCHAR(100) NOT NULL
# USERNAME/EMAIL VARCHAR(100) NOT NULL
# PASSWORD VARCHAR(100) NOT NULL
# * BooksBorrowed RELATIONSHIP to BOOK_ISSUE
# TotalBooksBorrowed INT NOT NULL

## SECTION
# ID PRIMARY KEY , UNIQUE, AUTOINCREMENT, NOT NULL
# Librarian ID  NOT NULL FOREIGN KEY
# Name VARCHAR(100) NOT NULL
# Date_created DATETIME NOT NULL
# Description VARCHAR(100) NOT NULL
# * Books RELATIONSHIP to BOOK

## BOOK
# ID PRIMARY KEY , UNIQUE, AUTOINCREMENT, NOT NULL
# Name VARCHAR(100) NOT NULL
# Content VARCHAR(100) NOT NULL *** issue regarding format ***
# Author(s) VARCHAR(100) NOT NULL
# Section ID * FOREIGN KEY
# Librarian ID * FOREIGN KEY
# NoPages INT NOT NULL
# Date_created DATETIME NOT NULL
# Description VARCHAR(100) NOT NULL
# Rating INT NOT NULL
# * Reviews RELATIONSHIP to REVIEW
# Cover *** issue
# PDF *** issue

## REVIEW
# ID PRIMARY KEY , UNIQUE, AUTOINCREMENT, NOT NULL
# Book ID FOREIGN KEY
# User ID FOREIGN KEY
# Content VARCHAR(100) NOT NULL

## BOOK_ISSUE
# ID PRIMARY KEY , UNIQUE, AUTOINCREMENT, NOT NULL
# Book ID FOREIGN KEY 
# User ID FOREIGN KEY
# Librarian ID FOREIGN KEY
# Date requested DATETIME NOT NULL
# Date issued DATETIME NOT NULL
# Return date DATETIME NOT NULL
# Status ENUM('REQUESTED','REJECTED','ISSUED','RETURNED','REVOKED') NOT NULL  // Status Revoked automatically if the return date is passed
